apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "my-jenkins.fullname" . }}
  labels:
    app: {{ include "my-jenkins.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "my-jenkins.fullname" . }}
  template:
    metadata:
      labels:
        app: {{ include "my-jenkins.fullname" . }}
    spec:
      containers:
        - name: jenkins
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: JAVA_OPTS
              value: "-Djenkins.install.runSetupWizard=false"
          ports:
            - containerPort: 8080
              name: http
          volumeMounts:
            - mountPath: /var/jenkins_home
              name: jenkins-home
      volumes:
        - name: jenkins-home
          persistentVolumeClaim:
            claimName: jenkins-home-claim
