apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "my-jenkins.fullname" . }}
  annotations: {{- toYaml .Values.ingress.annotations | nindent 4 }}
spec:
  rules:
    - host: {{ .Values.ingress.hosts[0].host }}
      http:
        paths:
          - path: {{ .Values.ingress.hosts[0].paths[0] }}
            pathType: {{ .Values.ingress.pathType }}
            backend:
              service:
                name: {{ include "my-jenkins.fullname" . }}
                port:
                  number: 8080
  {{- if .Values.ingress.tls }}
  tls:
    - hosts:
        - {{ .Values.ingress.hosts[0].host }}
      secretName: jenkins-tls
  {{- end }}
