apiVersion: v1
kind: PersistentVolume
metadata:
  name: jenkins-pv
spec:
  capacity:
    storage: 8Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: standard  # This should match the PVC's storageClassName
  hostPath:
    path: /mnt/data/jenkins  # Path on the node (adjust based on your environment)
